global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'scrapper_prometheus_monitoring'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'bot_prometheus_monitoring'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]
