app:
  test: "Something in the way..."
  scheduler:
    interval: 60000
  oldLinkInterval: 1
  databaseAccessType: jdbc
  queueName: scrapperQueue
  exchangeName: scrapperExchange
  useQueue: true

server:
  port: 8081

springdoc:
  swagger-ui:
    path: "/swagger-ui"

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5433/scrapper
    username:
    password:
    driverClassName: org.postgresql.Driver

management:
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 8082
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
      path-mapping:
        prometheus: metrics
