app:
  test: "Something in the way..."
  queueName: scrapperQueue
  exchangeName: scrapperExchange

bot:
  token:

scrapper:
  baseUrl: "http://localhost:8081"  # базовый URL для scrapper client

springdoc:
  swagger-ui:
    path: "/swagger-ui"



spring:
  application:
    name: bot
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 1

management:
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 8083
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
      path-mapping:
        prometheus: metrics
