app:
  test: "Something in the way..."
  queueName: scrapperQueue
  exchangeName: scrapperExchange

bot:
  token:

scrapper:
  baseUrl: "http://localhost:8081"  # базовый URL для scrapper client

springdoc:
  swagger-ui:
    path: "/swagger-ui"



spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 1